---
- block:
  - name: install python components
    apt: "pkg={{ item }} state=latest"
    with_items:
      - python-virtualenv
      - python3
      - python3-dev
      - build-essential
  tags:
    - python
