---
- block:
  - name: install python3 packages
    apt: "pkg={{ packages }} state=latest"
      pkg:
      - python3
      - python3-venv
      - python3-pip
      - python3-dev
      - build-essential
  tags:
    - python3
