---
- block:
  - name: install python3 packages
    ansible.builtin.apt:
      pkg:
        - python3
        - python3-venv
        - python3-pip
        - python3-dev
        - build-essential
      state: latest
  tags:
    - python3
