---
- block:
  - name: install python3 packages
    apt: "pkg={{ item }} state=latest"
    with_items:
      - python3
      - python3-venv
      - python3-dev
      - build-essential
  tags:
    - python3
